// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Certify.Domain.Entities;

public partial class BannerInfo
{
    public int BannerId { get; set; }

    public string Title { get; set; }

    public string Content { get; set; }

    public string ImageUrl { get; set; }

    public bool IsActive { get; set; }

    public DateTime DisplayFrom { get; set; }

    public DateTime DisplayTo { get; set; }

    public DateTime CreatedOn { get; set; }
}