// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Certify.Domain.Entities;

public partial class ContactU
{
    public int ContactUsId { get; set; }

    public string UserName { get; set; }

    public string UserEmail { get; set; }

    public string MessageDetail { get; set; }
}