// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Certify.Domain.Entities;

public partial class Exam
{
    public int ExamId { get; set; }

    public int CourseId { get; set; }

    public int UserId { get; set; }

    public string Status { get; set; }

    public DateTime StartedOn { get; set; }

    public DateTime? FinishedOn { get; set; }

    public string Feedback { get; set; }

    public virtual Course Course { get; set; }

    public virtual ICollection<ExamQuestion> ExamQuestions { get; set; } = new List<ExamQuestion>();

    public virtual UserProfile User { get; set; }
}