// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Certify.Domain.Entities;

public partial class ExamQuestion
{
    public int ExamQuestionId { get; set; }

    public int ExamId { get; set; }

    public int QuestionId { get; set; }

    public int? SelectedChoiceId { get; set; }

    public bool? IsCorrect { get; set; }

    public bool? ReviewLater { get; set; }

    public virtual Exam Exam { get; set; }

    public virtual Question Question { get; set; }

    public virtual Choice SelectedChoice { get; set; }
}