// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Certify.Domain.Entities;

public partial class Notification
{
    public int NotificationId { get; set; }

    public string Subject { get; set; }

    public string Content { get; set; }

    public DateTime CreatedOn { get; set; }

    public DateTime ScheduledSendTime { get; set; }

    public bool IsActive { get; set; }

    public virtual ICollection<UserNotification> UserNotifications { get; set; } = new List<UserNotification>();
}