// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Certify.Domain.Entities;

public partial class Question
{
    public int QuestionId { get; set; }

    public int CourseId { get; set; }

    public string QuestionText { get; set; }

    public string DifficultyLevel { get; set; }

    public bool IsCode { get; set; }

    public bool HasMultipleAnswers { get; set; }

    public virtual ICollection<Choice> Choices { get; set; } = new List<Choice>();

    public virtual Course Course { get; set; }

    public virtual ICollection<ExamQuestion> ExamQuestions { get; set; } = new List<ExamQuestion>();
}