// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Certify.Domain.Entities;

public partial class UserActivityLog
{
    public int LogId { get; set; }

    public int? UserId { get; set; }

    public string ActivityType { get; set; }

    public string ActivityDescription { get; set; }

    public DateTime LogDate { get; set; }

    public virtual UserProfile User { get; set; }
}