// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Certify.Domain.Entities;

public partial class UserNotification
{
    public int UserNotificationId { get; set; }

    public int NotificationId { get; set; }

    public int UserId { get; set; }

    public string EmailSubject { get; set; }

    public string EmailContent { get; set; }

    public bool NotificationSent { get; set; }

    public DateTime? SentOn { get; set; }

    public DateTime CreatedOn { get; set; }

    public virtual Notification Notification { get; set; }

    public virtual UserProfile User { get; set; }
}